version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile-edith
    ports:
      - "33333:33333"
    restart: unless-stopped
    environment:
      DELAY: 250
      enable_discord: 0 # 1 to enable bikerinfo
      discord: "key"
      # channel ids to rename
      warehouse_guns: 0
      warehouse_all: 0 
      capture_next: 0
      capture_emojis: 0
      capture_info: 0
      capture_status: 0
      capture_letters: 0
      # current club
      curb: "Name MC"
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - .:/sanic
  update-whitelist:
    build:
      context: .
      dockerfile: docker/Dockerfile-whitelist
    restart: unless-stopped
    environment:
      DELAY_IN_SECONDS: 300
      WHITELIST_RAW_LINK: "https://friendpaste.com/ID/raw"
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - ./config:/config
  update-twinks:
    build:
      context: .
      dockerfile: docker/Dockerfile-twinks
    restart: unless-stopped
    environment:
      DELAY_IN_SECONDS: 300
      TWINKS_RAW_LINK: "https://friendpaste.com/ID/raw"
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - ./config:/config
