version: "3.8"

services:
  server:
    build:
      context: backend
      dockerfile: docker/Dockerfile-edith
    ports:
      - "33333:33333"
    restart: unless-stopped
    environment:
      DELAY: 500
      # enable bikerinfo
      enable_bikerinfo: 0
      warehouse_guns: 0
      warehouse_all: 0
      capture_next: 0
      capture_emojis: 0
      capture_info: 0
      capture_status: 0
      capture_letters: 0
      # enable captureinfo
      enable_captureinfo: 0
      capture_channel: 0
      # enable top discord
      enable_top: 0
      top_channel: 0
      channel_flood: 0
      top_name: "edith"
      top_link: "http://URL:PORT/top"
      # discord bot api key for bikerinfo & captureinfo
      discord: "key"
      top_link_discord: "link to discord channel with top"
      # webhook url to send user's crash reports to
      crash_webhook: "discord webhook url"
      # current club, used for bikerinfo & captureinfo
      curb: "Name MC"
      # sentry
      enable_sentry: 0
      sentry_dsn: "https://public@sentry.example.com/1"
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - ./backend:/sanic
      - .:/static
  discord-jb:
    build:
      context: backend
      dockerfile: docker/Dockerfile-jb
    restart: unless-stopped
    environment:
      # enable jb notification service (depends on whitelist.txt, twinks.json, discord.json)
      enable_jb: 0
      channel_jb: 0
      # discord bot api key for jb reporting
      discord_jb: "key"
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - ./backend:/sanic
  # update whitelist.txt every 300 seconds
  update-whitelist:
    build:
      context: backend
      dockerfile: docker/Dockerfile-whitelist
    restart: unless-stopped
    environment:
      DELAY_IN_SECONDS: 300
      WHITELIST_RAW_LINK: "https://friendpaste.com/ID/raw"
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - ./backend/config:/config
  # update twinks.json every 300 seconds
  update-twinks:
    build:
      context: backend
      dockerfile: docker/Dockerfile-twinks
    restart: unless-stopped
    environment:
      DELAY_IN_SECONDS: 300
      TWINKS_RAW_LINK: "https://friendpaste.com/ID/raw"
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - ./backend/config:/config
  # update discord.json every 300 seconds
  update-discord:
    build:
      context: backend
      dockerfile: docker/Dockerfile-discord
    restart: unless-stopped
    environment:
      DELAY_IN_SECONDS: 300
      WHITELIST_RAW_LINK: "https://friendpaste.com/ID/raw"
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - ./backend/config:/config
